apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgres-main
    type: postgres
    access: proxy
    url: ${POSTGRES__HOST}:${POSTGRES__PORT}
    user: ${POSTGRES__USER}
    secureJsonData:
      password: ${POSTGRES__PASSWORD}
    jsonData:
      database: ${POSTGRES__NAME}
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
    editable: false
